# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-11 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PG_punishment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='pun_4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pun_5',
        ),
    ]
