# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-11 10:00
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PG_punishment', '0002_auto_20181011_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='punishment_received',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='punishment_sent',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
